Fix usage with jwk.
tsndr/cloudflare-worker-jwt pull request #26
Opened 2022-11-16 02:47 UTC by Manouchehri

2022-11-16 03:14 UTC, Manouchehri commented
Tested locally and it resolves #18.

```sh
git clone https://github.com/Manouchehri/cloudflare-worker-jwt.git
cd cloudflare-worker-jwt/
yarn install
yarn run build
yarn link
cd ../ # or go to whenever you're trying to test my fork from
yarn link "@tsndr/cloudflare-worker-jwt"
```

2022-11-24 23:18 UTC, tsndr requested changes

2022-11-24 23:18 UTC, tsndr commented on src/index.ts
> +    if (typeof secret === 'object') {
According to the type definitions `secret` can only be a `string`. This should be typed correctly.

2022-11-24 23:18 UTC, tsndr commented on src/index.ts
> -
This should be modified and not removed.

2022-11-24 23:18 UTC, tsndr commented on src/index.ts
> -
This should be modified and not removed.

2022-11-24 23:18 UTC, tsndr commented on src/index.ts
> +    if (typeof secret === 'object') {
According to the type definitions `secret` can only be a `string`. This should be typed correctly.

2022-11-24 23:20 UTC, tsndr commented
Thank you for your contribution, just a few changes, and then we should be good to merge 😉

2022-11-29 08:21 UTC, neves commented
Great, I just need that to validate Google JWT https://developers.google.com/identity/gsi/web/guides/verify-google-id-token
What's the estimation to merge that?

2022-11-29 12:20 UTC, tsndr commented
Will review either today or tomorrow :)

2022-12-07 16:57 UTC, Manouchehri commented
I ended up switching to jose, since it worked better for my specific use-case.

2022-12-07 16:58 UTC, closed without merging

2022-12-09 02:25 UTC, neves commented
@tsndr can we reopen this, I still need this feature, otherwise I can work on my fork.